name: Handle Issue Comment

on:
  issue_comment:
    types: [created,deleted]

jobs:
  build:
    if: github.event.comment.body == 'I want to solve this issue'

    runs-on: ubuntu-latest

    steps:
    - name: Post Issue comment
      uses: ibakshay/commentcreator@releases/v1

      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        message: 'Thank you very much. Please fork this repository and raise the PR when ready '
