
name: "CLA Assistant"
on:
  pull_request:
    
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "CLA Assistant"
      #if: github.event.action == 'opened' || github.event.action == 'synchronize'
      uses: ibakshay/action-template@dev-release
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        pathtocla: 'signatures/cla.json'
        branch: 'master'

